### ISSUE TITLE
how do I run the test suite?

### ISSUE THREAD

**Issue by ngpestelos** [jagthedrummer/so_auth#2]
I tried running `bundle exec rspec spec` and it's missing an environment file (see screenshot).

https://www.dropbox.com/s/e6err0xsriow99m/Screenshot%202014-06-17%2012.55.13.png

**Comment by jagthedrummer** [comment]
Well, it looks like I added rspec to this project, but never got around to actually making it run or writing any tests.  I'll try to get rspec running so that tests _could_ be added if someone were to want to do it, but you're not missing anything right now.
